name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Build the Docker image"
      run: docker build . --file Dockerfile --tag mkoellges/wildfly:21.0

    - name: "Run the image"
      run: docker-compose up -d && sleep 30

    - name: "Test the image"
      run: curl http://localhost:8080/check.html

    - name: "Login to DockerHub"
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: "Push to Docker Hub"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: mkoellges/wildfly:21.0
        tag_with_ref: true
      

  