name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mkoellges/wildfly:21.0

  run:

    runs-on: ubuntu-latest

    steps:
    - name: Run the image
      run: docker-compose up -d && sleep 30
    - name: test the image
      run: curl http://localhost:8080/check.html

  